# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: True
  config:
    entity: unnat-par-new-york-university-org
    project: lewm-jamba
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False