_target_: jepa.JEPA

encoder:
  _target_: module.JambaEncoder
  image_size: ${img_size}
  output_dim: ${embed_dim}
  hidden_size: 288
  intermediate_size: 1152
  num_hidden_layers: 10
  num_attention_heads: 8
  num_key_value_heads: 4
  attn_layer_period: 10
  attn_layer_offset: 9
  mamba_d_state: 16
  mamba_d_conv: 4
  mamba_expand: 2

predictor:
  _target_: module.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: module.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
